# Site settings
title: hanieh vahedi | هانیه واحدی
email: hi@hvahedi.ir
description: دانشجوی کارشناسی ترم افزار
baseurl: "http://hvahedi.ir"
url: "http://hvahedi.ir"
twitter: _vahedi
github:  hvahedi
behance: hvahedi
# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
exclude: ["node_modules", "gulpfile.js", "package.json"]